# Prompting Flan-T5

In [1]:
!pip install transformers tensorflow

In [2]:
from transformers import TFAutoModelForSeq2SeqLM, AutoTokenizer

# Load the tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-large")
model = TFAutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-large")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.13G [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
All PyTorch model weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


## Summarization

In [6]:
# Define the prompt
prompt = "summarize: Studies show that eating carrots helps improve vision. Carrots contain beta-carotene, a substance that the body converts into vitamin A, crucial for maintaining healthy eyesight."

# Generate inputs
inputs = tokenizer(prompt, return_tensors="tf", max_length=512, truncation=True, padding=True)

# Generate outputs
outputs = model.generate(inputs["input_ids"], max_length=150, num_beams=10, early_stopping=True)

# Decode and print the summary
print(tokenizer.decode(outputs[0], skip_special_tokens=True))


Eat carrots.


In [7]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 43), dtype=int32, numpy=
array([[21603,    10,  6536,   504,    24,  3182, 15578,     7,  1691,
         1172,  2267,     5,  1184,  2719,     7,  3480, 12637,    18,
         1720,    32,   324,    15,     6,     3,     9,  8096,    24,
            8,   643,  5755,     7,   139,  7869,    71,     6,  4462,
           21,  6011,  1695,  2053,  2632,     5,     1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 43), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
      dtype=int32)>}

In [8]:
outputs

<tf.Tensor: shape=(1, 11), dtype=int32, numpy=
array([[    0, 13808, 15578,     7,     5,     1,     0,     0,     0,
            0,     0]], dtype=int32)>

## Translation

In [4]:
# Define the translation prompt
translation_prompt = "translate English to Spanish: Cheese is delicious."

# Prepare inputs and generate outputs
translation_inputs = tokenizer(translation_prompt, return_tensors="tf", max_length=512, truncation=True, padding=True)
translation_outputs = model.generate(translation_inputs["input_ids"], max_length=40, num_beams=5, early_stopping=True)

# Decode and display the translation
print(tokenizer.decode(translation_outputs[0], skip_special_tokens=True))

El queso es delicioso.


## Q&A

In [5]:
# Define the context and question
context_question = "The Great Wall of China is over 13,000 miles long. question: How long is the Great Wall of China?"

# Generate inputs
question_inputs = tokenizer(context_question, return_tensors="tf", max_length=512, truncation=True, padding=True)

# Generate outputs
question_outputs = model.generate(question_inputs["input_ids"], max_length=50, num_beams=5, early_stopping=True)

# Decode and print the answer
print(tokenizer.decode(question_outputs[0], skip_special_tokens=True))


over 13,000 miles
